# == Variables ==
# 
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# add an additional ‘variables.yaml’ file in a subdirectory in the ‘Config’ folder: 
# '<project>/Config/_<environment>/variables.yaml
#
Variables:
  LdapConnector:
    Username: ""
    Password: ""
    Provider: "com.sun.jndi.ldap.LdapCtxFactory"
    Referral: "follow"
    Url: "ldap://159.100.249.76:389"
    Connection.Timeout: "1000"
