Variables:
  LdapConnector:
    # Ldap service provider
    Provider: "com.sun.jndi.ldap.LdapCtxFactory"
    # Url needed to contact the service provider, e.g. ldap://ldap.zug.ivy:389
    Url: ""
    # Username and password for contacting the service provider.
    Username: ""
    # [password]
    Password: ""
    # Determines how referrals are handled by the service provider. Possible values are "follow", "ignore" or "throw".
    Referral: "follow"
    Connection:
    # Timeout for Ldap operations
      Timeout: "1000"